### ISSUE TITLE
Use tools to compile and generate the rpm package of version 6.26.1 and report an error

### ISSUE THREAD

**Issue by 937988621** [greenplum-db/greenplum-database-release#326]
First, I pulled the latest gpdb 6.26.1 version code, then made it into a tar.gz package, and then executed the following command:

export BIN_GPDB_TARGZ=/root/20240204/gpdb.tar.gz
export CENTOS_VERSION=7
export GPDB_VERSION=6.26.1
make local-build-gpdb-rpm

As a result, the following error was generated, prompting me that the "./etc/git-info.json" file was missing in the code. The specific error was as follows:

.............
./gpdb/config/install-sh
./gpdb/config/general.m4
./gpdb/config/curl.m4
./gpdb/config/ac_func_accept_argtypes.m4
./gpdb/config/c-library.m4
./gpdb/config/cxx-compiler.m4
./gpdb/config/ax_python_module.m4
./gpdb/config/prep_buildtree
./gpdb/config/python.m4
./gpdb/config/test_quiet_include.h
./gpdb/config/ax_pthread.m4
./gpdb/config/ax_cxx_compile_stdcxx.m4
./gpdb/config/c-compiler.m4
./gpdb/config/Makefile
./gpdb/README.md
Traceback (most recent call last):
  File "/tmp/greenplum-database-release/ci/concourse/scripts/build-gpdb-rpm.py", line 50, in <module>
    rpm_builder.build()
  File "/tmp/greenplum-database-release/ci/concourse/oss/rpmbuild.py", line 64, in build
    build_flags = self._build_rpm_build_flags()
  File "/tmp/greenplum-database-release/ci/concourse/oss/rpmbuild.py", line 155, in _build_rpm_build_flags
    r'--define="rpm_gpdb_version %s"' % self.rpm_gpdb_version,
  File "/tmp/greenplum-database-release/ci/concourse/oss/rpmbuild.py", line 78, in rpm_gpdb_version
    return self.gpdb_version_short.replace('-', '_')
  File "/tmp/greenplum-database-release/ci/concourse/oss/base.py", line 25, in gpdb_version_short
    self._gpdb_version_short = Util.extract_gpdb_version(self.bin_gpdb_path)
  File "/tmp/greenplum-database-release/ci/concourse/oss/utils.py", line 31, in extract_gpdb_version
    member = bin_gpdb_tar.getmember('./etc/git-info.json')
  File "/usr/lib64/python2.7/tarfile.py", line 1796, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename './etc/git-info.json' not found"
make[1]: *** [local-build-gpdb6-rpm] Error 1
make[1]: Leaving directory `/root/20240204/greenplum-database-release'
make: *** [local-build-gpdb-rpm] Error 2

**Comment by duhy-max** [comment]
I encountered the same error @937988621  
Did you solve it?

**Comment by 937988621** [comment]
Sorry, I didn't solve it
937988621
***@***.***
---- Replied Message ----
***@***.***>Date4/17/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [greenplum-db/greenplum-database-release] Use tools to compile and generate the rpm package of version 6.26.1 and report an error (Issue #326)
I encountered the same error @937988621
Did you solve it?

**Comment by duhy-max** [comment]
> 937988621

@937988621 
i modify this file  : 
ci/concourse/oss/base.py
`self._gpdb_version_short = None -- > self._gpdb_version_short = '6.26.1' `

then skip this error ，but now a new error occor .

**Comment by duhy-max** [comment]
2   注释： ext/python/bin/python -m compileall -q -x "(test|python3\.9)" .

这一步骤不用注释掉，要在二进制包中打进去就ok了。

**Comment by 937988621** [comment]
> 2 注释： ext/python/bin/python -m compileall -q -x "(test|python3.9)" .
> 
> 这一步骤不用注释掉，要在二进制包中打进去就ok了。

我最后使用下面的命令编译出来了，只不过少了其中python部分，我尝试将已发行的版本中python文件移植了过来，然后自己部署集群，目前没发现有什么问题
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/greenplum-db-6.26.1

**Comment by duhy-max** [comment]
> > 2 注释： ext/python/bin/python -m compileall -q -x "(test|python3.9)" .
> > 这一步骤不用注释掉，要在二进制包中打进去就ok了。
> 
> 我最后使用下面的命令编译出来了，只不过少了其中python部分，我尝试将已发行的版本中python文件移植了过来，然后自己部署集群，目前没发现有什么问题 ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/greenplum-db-6.26.1

并不是少了`其中python部分`吧，我对比bin文件夹下的文件个数，和有一些命令文件的大小也是不一样的。

```
-rwxr-xr-x 1 root root  67K 4月  18 16:21 analyzedb
-rwxr-xr-x 1 root root  75K 4月  18 16:21 clusterdb
-rwxr-xr-x 1 root root  75K 4月  18 16:21 createdb
-rwxr-xr-x 1 root root 104K 4月  18 16:21 createlang
-rwxr-xr-x 1 root root  75K 4月  18 16:21 createuser
-rwxr-xr-x 1 root root  70K 4月  18 16:21 dropdb
-rwxr-xr-x 1 root root 104K 4月  18 16:21 droplang
-rwxr-xr-x 1 root root  70K 4月  18 16:21 dropuser
-rwxr-xr-x 1 root root 968K 4月  18 16:21 ecpg
-rwxr-xr-x 1 root root  16K 4月  18 16:21 gpactivatestandby
```
下面的官网给的：
```
-rwxr-xr-x 1 root root  67K 10月  7 2022 analyzedb
-rwxr-xr-x 1 root root 246K 10月  7 2022 clusterdb
-rwxr-xr-x 1 root root 242K 10月  7 2022 createdb
-rwxr-xr-x 1 root root 375K 10月  7 2022 createlang
-rwxr-xr-x 1 root root 245K 10月  7 2022 createuser
-rwxr-xr-x 1 root root 225K 10月  7 2022 dropdb
-rwxr-xr-x 1 root root 375K 10月  7 2022 droplang
-rwxr-xr-x 1 root root 225K 10月  7 2022 dropuser
-rwxr-xr-x 1 root root 2.2M 10月  7 2022 ecpg
-rwxr-xr-x 1 root root  16K 10月  7 2022 gpactivatestandby
```

**Comment by 937988621** [comment]
是的，文件虽然大小不一样，但是我尝试用自编译的greenplumdb去部署服务，部署出来的服务是正常的，目前没发现有什么报错
937988621
***@***.***
---- Replied Message ----
***@***.***>Date4/19/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [greenplum-db/greenplum-database-release] Use tools to compile and generate the rpm package of version 6.26.1 and report an error (Issue #326)
2 注释： ext/python/bin/python -m compileall -q -x "(test|python3.9)" .
这一步骤不用注释掉，要在二进制包中打进去就ok了。
我最后使用下面的命令编译出来了，只不过少了其中python部分，我尝试将已发行的版本中python文件移植了过来，然后自己部署集群，目前没发现有什么问题 ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/greenplum-db-6.26.1
并不是少了其中python部分吧，我对比bin文件夹下的文件个数，和有一些命令文件的大小也是不一样的。
-rwxr-xr-x 1 root root 67K 4月 18 16:21 analyzedb -rwxr-xr-x 1 root root 75K 4月 18 16:21 clusterdb -rwxr-xr-x 1 root root 75K 4月 18 16:21 createdb -rwxr-xr-x 1 root root 104K 4月 18 16:21 createlang -rwxr-xr-x 1 root root 75K 4月 18 16:21 createuser -rwxr-xr-x 1 root root 70K 4月 18 16:21 dropdb -rwxr-xr-x 1 root root 104K 4月 18 16:21 droplang -rwxr-xr-x 1 root root 70K 4月 18 16:21 dropuser -rwxr-xr-x 1 root root 968K 4月 18 16:21 ecpg -rwxr-xr-x 1 root root 16K 4月 18 16:21 gpactivatestandby 
下面的官网给的：
-rwxr-xr-x 1 root root 67K 10月 7 2022 analyzedb -rwxr-xr-x 1 root root 246K 10月 7 2022 clusterdb -rwxr-xr-x 1 root root 242K 10月 7 2022 createdb -rwxr-xr-x 1 root root 375K 10月 7 2022 createlang -rwxr-xr-x 1 root root 245K 10月 7 2022 createuser -rwxr-xr-x 1 root root 225K 10月 7 2022 dropdb -rwxr-xr-x 1 root root 375K 10月 7 2022 droplang -rwxr-xr-x 1 root root 225K 10月 7 2022 dropuser -rwxr-xr-x 1 root root 2.2M 10月 7 2022 ecpg -rwxr-xr-x 1 root root 16K 10月 7 2022 gpactivatestandby
